key: value
name: hashtable
alias: map
list: [1, 2, 3]
json_map: {"key": "value"
           "key2": "value2" 
           "key3": "value3"}
json_list: ["value1", "value2", "value3"]
boolean: true
also_true: yes
false: false
also_false: no

# indention : 2 spaces
sequence:
  - one
  - two
  - three

literal_block: |
  This is a literal block
  It has multiple lines
  It preserves whitespace

folded_block: >
  This is a folded block
  It has multiple lines
  It folds newlines into spaces

# optional: yaml in y minutes (https://learnxinyminutes.com/docs/yaml/)
